version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: royalvault-db
    environment:
      POSTGRES_USER: royalvault
      POSTGRES_PASSWORD: royalvault
      POSTGRES_DB: royalvault
    ports:
      - "5432:5432"
    volumes:
      - royalvault_data:/var/lib/postgresql/data

volumes:
  royalvault_data:
